### ISSUE TITLE
CLI command to summarize the Project is Failing

### ISSUE THREAD

**Issue by tcchawla** [khromov/ai-digest#2]
When I run the command `npx ai-digest` in my project, it is not able to generate the `codebase.md`. It gives out an error related to invalid string length

This is the exact error:
```
Found .aidigestignore file in /Users/desktop.
Ignore patterns from .aidigestignore:
  - node_modules
  - .env
  - .env.example
  - data/temp/
🚫 Using default ignore patterns.
🧹 Whitespace removal enabled (except for whitespace-dependent languages).
🔍 Found 23658 files in /Users/desktop. Applying filters...
❌ Error aggregating files: RangeError: Invalid string length
    at readFileHandle (node:internal/fs/promises:590:25)
    at async aggregateFiles (/Users/.npm/_npx/764439b5c8abeeaf/node_modules/ai-digest/dist/index.js:75:35)
    at async Command.<anonymous> (/Users/.npm/_npx/764439b5c8abeeaf/node_modules/ai-digest/dist/index.js:151:5)
```

**Comment by khromov** [comment]
@tcchawla Thanks for the bug report! Is it possible to provide the repository (or any repository) that triggers the above issue for you?

It sounds like it is related to either very large files, or files that have a strange non-utf8 encoding (although I haven't been able to reproduce this issue with a variety of different encodings). I see you're running the tool inside `/Users/desktop` and you might want to run it inside your project directory instead!

**Comment by khromov** [comment]
See possibly related: https://github.com/nodejs/node/issues/35973

**Comment by tcchawla** [comment]
Hey @khromov, thanks for referencing the similar issue. 

I switched to Node v20, and now it is working perfectly. It was node version error.
