### ISSUE TITLE
JS project with comments in code: \\

### ISSUE THREAD

**Issue by davie-robertson** [khromov/ai-digest#3]
Thank you for this great tool.  

Quick question for you, will the use of `\\` prefixed comments impact the use of the AI to understand code, for example here's my vite config file

![image](https://github.com/user-attachments/assets/152322b9-c591-4806-86ff-b69cfc4cb05a)

As you can see the use of `\\` makes the most of the files look like a comment.  I guess this is just a markdown issue rather than anything that  cause the AI API to ignore the code?

**Comment by khromov** [comment]
Thanks for your question. In my experience it doesn't matter much when it comes to code generation performance. I've even loaded in huge JSON blobs of documentation [like this](https://kit.svelte.dev/content.json) and that works fine. 

The problem with starting to modify files, removing comments etc is if you ask Claude to give you the file in full with some changes, you'll also get these unwanted modifications. So it's better to keep them as-is imho.

For the best result, you should not compress the output. It will be easier for you to get correctly formatted files out, and whitespace removal only saves ~10% on the token count.

**Comment by davie-robertson** [comment]
It seems ChatGPT has an issue with the comments, I'll try and change them all to  `/* and */` and see if that help

```
Sure, I can help you with that. Let's start by reviewing the contents of the project_summary.md file you uploaded to get an understanding of your project setup and requirements. I'll take a look at it now.

I'll read the contents of the file and provide feedback accordingly.

The contents of the file seem to be cut off and mixed with code snippets and documentation text. 

```

**Comment by khromov** [comment]
If you have issues with comments, try without whitespace removal! I'll close this for now, thanks for raising the issue! 🙇
